pipeline{
    agent{
    docker{
	image 'maven:3.6.1-jdk-8-slim'
	} 
}
    stages{
        stage(build)
        {
	when{
		changeset "**/worker/**"
	}
             steps
             {
		dir('worker'){
                    sh 'mvn compile'
		}
             }
        }
        stage(test)
        {
             steps
             {
                dir('worker'){
			sh 'mvn clean test'
		}
             }
        }
        stage(package)
        {
	when{
		branch 'master'
	}
             steps
             {
                dir('worker'){
			sh 'mvn package -Dskip test'
			archiveArtifacts '**/target/*.jar'
		}
             }
        }
       
    }
    post{
        always{
            echo 'Completed'
        }
    }
}
