pipeline{
    agent any
    tools{
	maven 'maven 3.6.1'
	} 

    stages{
        stage(build)
        {
             steps
             {
		dir('worker'){
                    sh 'mvn compile'
		}
             }
        }
        stage(two)
        {
             steps
             {
                echo 'Stage 2'
                sleep 5
             }
        }
        stage(three)
        {
             steps
             {
                echo 'Stage 3'
                sleep 3
             }
        }
       
    }
    post{
        always{
            echo "This pipeline is completed"
        }
    }
}
